### ISSUE TITLE
[PE-D][Tester F] Sort command should work as expected by the user.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T15-4/tp#163]
The sort command works as expected, according to the User Guide.

However, the user would expect the `sort` command to work differently without reading the User Guide, e.g. group exercises together from the user's side for a more pleasant experience.

![Screenshot 2022-10-28 at 4.58.18 PM.png](https://raw.githubusercontent.com/snigloo/ped/main/files/78145fa1-2208-4e6c-a998-3c597ef92848.png)

The exercise list should already be sorted by the most recent date as default.

The most recent exercise to the current date should be at the top when doing `:list`, and the `sort` command can be used for a feature that enhances the product or be removed completely.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: snigloo/ped#4

**Comment by 24Donovan24** [comment]
Not sure what the rest think of this bug? In my opinion, I don't see this as a bug.
1. "grouping exercises together ..." seems just like `:find` command that we already have.
2. "exercise list should already be sorted by the most recent date as default." I believe our reason of not doing so is so that exercises are listed according to **date of input** and not **date of completion**.
3. "The most recent exercise to the current date should be at the top when doing `:list`..." Same point as **2.**

**Comment by ErvinK123** [comment]
Similar to #162

**Comment by ee-suan** [comment]
Closed by #190
